# shortcut to this dotfiles path is $ZSH
# export ZSH=$HOME/.dotfiles

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

source ~/.dotfiles/zsh/aliases.zsh
source ~/.dotfiles/zsh/completion.zsh
source ~/.dotfiles/zsh/config.zsh
source ~/.dotfiles/zsh/env.zsh
source ~/.dotfiles/zsh/grc.zsh
source ~/.dotfiles/zsh/path.zsh

